// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (workspace_id, database_id, key_hash, key_prefix, name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, database_id, key_prefix, name, created_at
`

type CreateAPIKeyParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	DatabaseID  pgtype.UUID `json:"database_id"`
	KeyHash     string      `json:"key_hash"`
	KeyPrefix   string      `json:"key_prefix"`
	Name        string      `json:"name"`
}

type CreateAPIKeyRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	DatabaseID  pgtype.UUID        `json:"database_id"`
	KeyPrefix   string             `json:"key_prefix"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.WorkspaceID,
		arg.DatabaseID,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Name,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DatabaseID,
		&i.KeyPrefix,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = $1 AND workspace_id = $2
`

type DeleteAPIKeyParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.WorkspaceID)
	return err
}

const listAPIKeysByWorkspace = `-- name: ListAPIKeysByWorkspace :many
SELECT id, key_prefix, name, database_id, expires_at, last_used_at, created_at
FROM api_keys
WHERE workspace_id = $1
ORDER BY created_at DESC
`

type ListAPIKeysByWorkspaceRow struct {
	ID         pgtype.UUID        `json:"id"`
	KeyPrefix  string             `json:"key_prefix"`
	Name       string             `json:"name"`
	DatabaseID pgtype.UUID        `json:"database_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAPIKeysByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]ListAPIKeysByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysByWorkspaceRow{}
	for rows.Next() {
		var i ListAPIKeysByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyPrefix,
			&i.Name,
			&i.DatabaseID,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}

const validateAPIKey = `-- name: ValidateAPIKey :one
SELECT id, workspace_id, name, database_id
FROM api_keys
WHERE key_hash = $1
  AND (expires_at IS NULL OR expires_at > now())
`

type ValidateAPIKeyRow struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	DatabaseID  pgtype.UUID `json:"database_id"`
}

func (q *Queries) ValidateAPIKey(ctx context.Context, keyHash string) (ValidateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, validateAPIKey, keyHash)
	var i ValidateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.DatabaseID,
	)
	return i, err
}
