// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_logs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertQueryLog = `-- name: InsertQueryLog :exec
INSERT INTO query_logs (workspace_id, database_id, key_id, tool_name, tool_input, duration_ms, is_error)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertQueryLogParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	DatabaseID  pgtype.UUID `json:"database_id"`
	KeyID       pgtype.UUID `json:"key_id"`
	ToolName    string      `json:"tool_name"`
	ToolInput   pgtype.Text `json:"tool_input"`
	DurationMs  int32       `json:"duration_ms"`
	IsError     bool        `json:"is_error"`
}

func (q *Queries) InsertQueryLog(ctx context.Context, arg InsertQueryLogParams) error {
	_, err := q.db.Exec(ctx, insertQueryLog,
		arg.WorkspaceID,
		arg.DatabaseID,
		arg.KeyID,
		arg.ToolName,
		arg.ToolInput,
		arg.DurationMs,
		arg.IsError,
	)
	return err
}

const listQueryLogs = `-- name: ListQueryLogs :many
SELECT id, workspace_id, database_id, key_id, tool_name, tool_input, duration_ms, is_error, created_at
FROM query_logs
WHERE workspace_id = $1
  AND ($2::UUID IS NULL OR database_id = $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListQueryLogsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	DatabaseID  pgtype.UUID `json:"database_id"`
	ResultLimit int32       `json:"result_limit"`
}

func (q *Queries) ListQueryLogs(ctx context.Context, arg ListQueryLogsParams) ([]QueryLog, error) {
	rows, err := q.db.Query(ctx, listQueryLogs, arg.WorkspaceID, arg.DatabaseID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueryLog{}
	for rows.Next() {
		var i QueryLog
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DatabaseID,
			&i.KeyID,
			&i.ToolName,
			&i.ToolInput,
			&i.DurationMs,
			&i.IsError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
