// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (key_hash, key_prefix, name)
VALUES ($1, $2, $3)
RETURNING id, key_prefix, name, is_active, created_at
`

type CreateAPIKeyParams struct {
	KeyHash   string `json:"key_hash"`
	KeyPrefix string `json:"key_prefix"`
	Name      string `json:"name"`
}

type CreateAPIKeyRow struct {
	ID        pgtype.UUID        `json:"id"`
	KeyPrefix string             `json:"key_prefix"`
	Name      string             `json:"name"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey, arg.KeyHash, arg.KeyPrefix, arg.Name)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.KeyPrefix,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, key_prefix, name, is_active, created_at, last_used_at, revoked_at
FROM api_keys
ORDER BY created_at DESC
`

type ListAPIKeysRow struct {
	ID         pgtype.UUID        `json:"id"`
	KeyPrefix  string             `json:"key_prefix"`
	Name       string             `json:"name"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyPrefix,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET is_active = FALSE, revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, id)
	return err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}

const validateAPIKey = `-- name: ValidateAPIKey :one
SELECT id, name, is_active
FROM api_keys
WHERE key_hash = $1 AND is_active = TRUE AND revoked_at IS NULL
`

type ValidateAPIKeyRow struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) ValidateAPIKey(ctx context.Context, keyHash string) (ValidateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, validateAPIKey, keyHash)
	var i ValidateAPIKeyRow
	err := row.Scan(&i.ID, &i.Name, &i.IsActive)
	return i, err
}
