// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: databases.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDatabase = `-- name: CreateDatabase :one
INSERT INTO databases (workspace_id, name, connection_type, status)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, name, connection_type, status, created_at, updated_at
`

type CreateDatabaseParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	Name           string      `json:"name"`
	ConnectionType string      `json:"connection_type"`
	Status         string      `json:"status"`
}

type CreateDatabaseRow struct {
	ID             pgtype.UUID        `json:"id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	Name           string             `json:"name"`
	ConnectionType string             `json:"connection_type"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateDatabase(ctx context.Context, arg CreateDatabaseParams) (CreateDatabaseRow, error) {
	row := q.db.QueryRow(ctx, createDatabase,
		arg.WorkspaceID,
		arg.Name,
		arg.ConnectionType,
		arg.Status,
	)
	var i CreateDatabaseRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ConnectionType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDatabaseWithURL = `-- name: CreateDatabaseWithURL :one
INSERT INTO databases (workspace_id, name, connection_type, encrypted_connection_url, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, name, connection_type, status, created_at, updated_at
`

type CreateDatabaseWithURLParams struct {
	WorkspaceID            pgtype.UUID `json:"workspace_id"`
	Name                   string      `json:"name"`
	ConnectionType         string      `json:"connection_type"`
	EncryptedConnectionUrl []byte      `json:"encrypted_connection_url"`
	Status                 string      `json:"status"`
}

type CreateDatabaseWithURLRow struct {
	ID             pgtype.UUID        `json:"id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	Name           string             `json:"name"`
	ConnectionType string             `json:"connection_type"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateDatabaseWithURL(ctx context.Context, arg CreateDatabaseWithURLParams) (CreateDatabaseWithURLRow, error) {
	row := q.db.QueryRow(ctx, createDatabaseWithURL,
		arg.WorkspaceID,
		arg.Name,
		arg.ConnectionType,
		arg.EncryptedConnectionUrl,
		arg.Status,
	)
	var i CreateDatabaseWithURLRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ConnectionType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDatabase = `-- name: DeleteDatabase :exec
DELETE FROM databases WHERE id = $1 AND workspace_id = $2
`

type DeleteDatabaseParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteDatabase(ctx context.Context, arg DeleteDatabaseParams) error {
	_, err := q.db.Exec(ctx, deleteDatabase, arg.ID, arg.WorkspaceID)
	return err
}

const getDatabaseByID = `-- name: GetDatabaseByID :one
SELECT id, workspace_id, name, connection_type, encrypted_connection_url, status, created_at, updated_at
FROM databases
WHERE id = $1
`

func (q *Queries) GetDatabaseByID(ctx context.Context, id pgtype.UUID) (Database, error) {
	row := q.db.QueryRow(ctx, getDatabaseByID, id)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ConnectionType,
		&i.EncryptedConnectionUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDatabasesByWorkspace = `-- name: ListDatabasesByWorkspace :many
SELECT id, workspace_id, name, connection_type, status, created_at, updated_at
FROM databases
WHERE workspace_id = $1
ORDER BY created_at DESC
`

type ListDatabasesByWorkspaceRow struct {
	ID             pgtype.UUID        `json:"id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	Name           string             `json:"name"`
	ConnectionType string             `json:"connection_type"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListDatabasesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]ListDatabasesByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listDatabasesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDatabasesByWorkspaceRow{}
	for rows.Next() {
		var i ListDatabasesByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ConnectionType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDatabaseStatus = `-- name: UpdateDatabaseStatus :exec
UPDATE databases SET status = $1, updated_at = now()
WHERE id = $2
`

type UpdateDatabaseStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateDatabaseStatus(ctx context.Context, arg UpdateDatabaseStatusParams) error {
	_, err := q.db.Exec(ctx, updateDatabaseStatus, arg.Status, arg.ID)
	return err
}
