// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :exec
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (workspace_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type AddWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Role        string      `json:"role"`
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, addWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (clerk_org_id, owner_user_id, name, is_personal)
VALUES ($1, $2, $3, $4)
RETURNING id, clerk_org_id, owner_user_id, name, is_personal, created_at
`

type CreateWorkspaceParams struct {
	ClerkOrgID  pgtype.Text `json:"clerk_org_id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	Name        string      `json:"name"`
	IsPersonal  bool        `json:"is_personal"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.ClerkOrgID,
		arg.OwnerUserID,
		arg.Name,
		arg.IsPersonal,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.ClerkOrgID,
		&i.OwnerUserID,
		&i.Name,
		&i.IsPersonal,
		&i.CreatedAt,
	)
	return i, err
}

const getPersonalWorkspace = `-- name: GetPersonalWorkspace :one
SELECT id, clerk_org_id, owner_user_id, name, is_personal, created_at
FROM workspaces
WHERE owner_user_id = $1 AND is_personal = TRUE
`

func (q *Queries) GetPersonalWorkspace(ctx context.Context, ownerUserID pgtype.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getPersonalWorkspace, ownerUserID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.ClerkOrgID,
		&i.OwnerUserID,
		&i.Name,
		&i.IsPersonal,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceByClerkOrgID = `-- name: GetWorkspaceByClerkOrgID :one
SELECT id, clerk_org_id, owner_user_id, name, is_personal, created_at
FROM workspaces
WHERE clerk_org_id = $1
`

func (q *Queries) GetWorkspaceByClerkOrgID(ctx context.Context, clerkOrgID pgtype.Text) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByClerkOrgID, clerkOrgID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.ClerkOrgID,
		&i.OwnerUserID,
		&i.Name,
		&i.IsPersonal,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, clerk_org_id, owner_user_id, name, is_personal, created_at
FROM workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id pgtype.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.ClerkOrgID,
		&i.OwnerUserID,
		&i.Name,
		&i.IsPersonal,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT workspace_id, user_id, role, created_at
FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type GetWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT w.id, w.clerk_org_id, w.owner_user_id, w.name, w.is_personal, w.created_at, wm.role
FROM workspaces w
JOIN workspace_members wm ON wm.workspace_id = w.id
WHERE wm.user_id = $1
ORDER BY w.created_at
`

type ListWorkspacesForUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	ClerkOrgID  pgtype.Text        `json:"clerk_org_id"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	Name        string             `json:"name"`
	IsPersonal  bool               `json:"is_personal"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Role        string             `json:"role"`
}

func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID pgtype.UUID) ([]ListWorkspacesForUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesForUserRow{}
	for rows.Next() {
		var i ListWorkspacesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ClerkOrgID,
			&i.OwnerUserID,
			&i.Name,
			&i.IsPersonal,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
